{{- if and .Values.gateway.enabled (eq .Values.layer "auth") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: {{ .Values.services.auth.replicas }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      {{- if .Values.istio.enabled }}
      annotations:
        sidecar.istio.io/inject: "true"
        {{- if .Values.istio.revision }}
        istio.io/rev: {{ .Values.istio.revision | quote }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - name: auth-service
        image: {{ .Values.image.authService }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.services.auth.port }}
          name: http
        livenessProbe:
          httpGet:
            path: {{ .Values.services.auth.livenessProbe.path }}
            port: {{ .Values.services.auth.port }}
          initialDelaySeconds: {{ .Values.services.auth.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.auth.livenessProbe.periodSeconds }}
          failureThreshold: 3
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: {{ .Values.services.auth.readinessProbe.path }}
            port: {{ .Values.services.auth.port }}
          initialDelaySeconds: {{ .Values.services.auth.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.auth.readinessProbe.periodSeconds }}
          failureThreshold: 3
          timeoutSeconds: 1
{{- end }}
---
{{- if and .Values.gateway.enabled (eq .Values.layer "auth") }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.auth.name }}
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
  type: ClusterIP
{{- end }}
