{{- if and .Values.gateway.enabled (eq .Values.environment "post-test") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: {{ .Values.services.auth.replicas }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: {{ .Values.image.auth-service }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.services.auth.port }}
          name: http
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.services.auth.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: 3
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.services.auth.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: 3
          timeoutSeconds: 1
{{- end }}
---
{{- if and .Values.gateway.enabled (eq .Values.environment "post-test") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.auth.name }}
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
  type: ClusterIP
{{- end }}
