apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  labels:
    app: billing-service
spec:
  replicas: {{ .Values.services.billing.replicas }}
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
      {{- if .Values.istio.enabled }}
      annotations:
        sidecar.istio.io/inject: "true"
        {{- if .Values.istio.revision }}
        istio.io/rev: {{ .Values.istio.revision | quote }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - name: billing-service
        image: {{ .Values.image.billingService }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.services.billing.port }}
          name: http
        livenessProbe:
          httpGet:
            path: {{ .Values.services.billing.livenessProbe.path }}
            port: {{ .Values.services.billing.port }}
          initialDelaySeconds: {{ .Values.services.billing.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.billing.livenessProbe.periodSeconds }}
          failureThreshold: 3
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: {{ .Values.services.billing.readinessProbe.path }}
            port: {{ .Values.services.billing.port }}
          initialDelaySeconds: {{ .Values.services.billing.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.billing.readinessProbe.periodSeconds }}
          failureThreshold: 3
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.billing.name }}
spec:
  selector:
    app: billing-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
  type: ClusterIP
