apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-api-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.apiGateway }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http-server
        livenessProbe:
          httpGet:
            path: {{ .Values.apiGateway.livenessProbe.path }}
            port: 9000
          initialDelaySeconds: {{ .Values.apiGateway.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiGateway.livenessProbe.periodSeconds }}
          failureThreshold: 3
          timeoutSeconds: 1

        readinessProbe:
          httpGet:
            path: {{ .Values.apiGateway.readinessProbe.path }}
            port: 9000
          initialDelaySeconds: {{ .Values.apiGateway.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiGateway.readinessProbe.periodSeconds }}
          failureThreshold: 3
          timeoutSeconds: 1

        