{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Release.Namespace }}-mtls-strict
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
{{- end }}
