---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: dev

patches:
  - target: { kind: Deployment, name: external-dns }
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: external-dns
      spec:
        template:
          spec:
            containers:
              - name: external-dns
                resources:
                  requests: { cpu: 25m, memory: 32Mi }
                  limits: { cpu: 50m, memory: 64Mi }
