--liquibase formatted sql
--
-- Full baseline schema for billing-service, derived from the JPA entities
-- (com.project.billing.adapter.out.persistence.*). Column names/types match Hibernate's
-- mapping (explicit @Column names on invoices; default snake_case on usage_charges) so
-- the app's ddl-auto=validate passes.
--
-- Safe on pre-existing databases: every object uses IF NOT EXISTS. Add new schema changes
-- as further changeSets below (never edit an already-applied changeSet — its checksum is
-- recorded in DATABASECHANGELOG).

-- changeset billing-service:001-create-invoices
CREATE TABLE IF NOT EXISTS invoices (
    invoice_id      uuid          NOT NULL PRIMARY KEY,
    subscription_id uuid          NOT NULL,
    customer_id     uuid          NOT NULL,
    amount          numeric(19,4) NOT NULL,
    currency        varchar(3)    NOT NULL,
    status          varchar(32)   NOT NULL,
    issued_at       timestamptz   NOT NULL,
    due_at          timestamptz   NOT NULL
);

-- changeset billing-service:002-create-usage-charges
CREATE TABLE IF NOT EXISTS usage_charges (
    id          uuid          PRIMARY KEY,
    invoice_id  uuid          NOT NULL,
    metric      varchar(255)  NOT NULL,
    quantity    bigint        NOT NULL,
    unit_price  numeric(38,2) NOT NULL,
    total_price numeric(38,2) NOT NULL,
    CONSTRAINT fk_usage_charges_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoices (invoice_id)
);

-- changeset billing-service:003-create-billing-event-store
-- Shared append-only event store: the write-side source of truth for the (now event-sourced)
-- Invoice and UsageCharge aggregates, discriminated by aggregate_type. The invoices/usage_charges
-- tables above are read-model projections rebuilt from these events.
-- (aggregate_type, aggregate_id, sequence) is unique — that constraint is the optimistic-concurrency
-- guard on append. global_seq is a store-wide order the outbox relay walks to publish to Kafka.
-- Column types match the JPA entity (com.project.billing.adapter.out.persistence.eventstore.BillingEventEntity)
-- so the app's ddl-auto=validate passes.
CREATE TABLE IF NOT EXISTS billing_event_store (
    global_seq     bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       uuid         NOT NULL,
    aggregate_type varchar(32)  NOT NULL,
    aggregate_id   uuid         NOT NULL,
    sequence       bigint       NOT NULL,
    event_type     varchar(64)  NOT NULL,
    payload        jsonb        NOT NULL,
    occurred_at    timestamptz  NOT NULL,
    published      boolean      NOT NULL DEFAULT false,
    published_at   timestamptz,
    CONSTRAINT uq_billing_event_stream_sequence UNIQUE (aggregate_type, aggregate_id, sequence),
    CONSTRAINT uq_billing_event_event_id UNIQUE (event_id)
);

-- changeset billing-service:004-index-billing-event-store-unpublished
-- Backs the relay's "next unpublished events in global order" query; partial index stays small.
CREATE INDEX IF NOT EXISTS billing_event_store_unpublished_idx
    ON billing_event_store (global_seq)
    WHERE published = false;

-- changeset billing-service:005-create-invoice-snapshot
-- One materialised Invoice state per invoice at a known version, to bound replay cost. Derived
-- data: safe to truncate and rebuild from billing_event_store. Matches InvoiceSnapshotEntity.
CREATE TABLE IF NOT EXISTS invoice_snapshot (
    aggregate_id uuid         NOT NULL PRIMARY KEY,
    version      bigint       NOT NULL,
    state        jsonb        NOT NULL,
    taken_at     timestamptz  NOT NULL
);
