---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
  - target: { kind: Deployment, name: nginx-gateway-nginx-gateway-fabric }
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-gateway-nginx-gateway-fabric
      spec:
        template:
          spec:
            containers:
              - name: nginx-gateway
                resources:
                  requests: { cpu: 50m, memory: 64Mi }
                  limits: { cpu: 250m, memory: 256Mi }
