apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application/applications.yaml
  - cert-manager/cert-manager.yaml
  - external-dns/external-dns.yaml
  - external-secret/external-secret.yaml
  - airflow/airflow.yaml
  - keycloak/keycloak-gateway.yaml
  - karpenter/karpenter.yaml
  - karpenter/nodepool.yaml
