---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: prod

patches:
  - target: { version: v1, kind: Service, name: nginx-gateway-lb }
    patch: |-
      - op: replace
        path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-scheme
        value: internal
