---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
  - target: { kind: Deployment, name: aws-lb-controller-aws-load-balancer-controller }
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: aws-lb-controller-aws-load-balancer-controller
      spec:
        template:
          spec:
            containers:
              - name: aws-load-balancer-controller
                resources:
                  requests: { cpu: 50m, memory: 64Mi }
                  limits: { cpu: 250m, memory: 128Mi }
