---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
  - target: { kind: Deployment, name: kibana-kibana }
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kibana-kibana
      spec:
        template:
          spec:
            containers:
              - name: kibana
                resources:
                  requests: { cpu: 200m, memory: 512Mi }
                  limits: { cpu: 500m, memory: 1Gi }
