{{- if .Values.gateway.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-backstage
spec:
  acme:
    email: huzaifagill411@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-backstage-private-key
    solvers:
      - dns01:
          route53:
            region: us-east-1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: backstage-tls
  issuerRef:
    name: letsencrypt-backstage
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.host | quote }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: backstage-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-backstage
spec:
  gatewayClassName: nginx
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.host | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: backstage-tls
            kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backstage
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: backstage-gateway
  hostnames:
    - {{ .Values.host | quote }}
  rules:
    - backendRefs:
        - name: backstage
          port: 7007
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    gateway.networking.k8s.io/gateway-name: backstage-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
{{- end }}
