---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: {{ .Release.Namespace }}
  labels:
    app: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 7007
      targetPort: 7007
      protocol: TCP
