---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: prod

patches:
  - target: { kind: Deployment, name: cert-manager }
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: cert-manager-controller
                resources:
                  requests: { cpu: 100m, memory: 256Mi }
                  limits: { cpu: 500m, memory: 512Mi }
