replicas: 3

image:
  repository: ""  
  tag: "prod"

istio:
  enabled: true
  revision: ""

blueGreen:
  activeSlot: blue
  previewSlot: green
  previewTag: "prod"
  activeWeight: 100
  previewWeight: 0

livenessProbe:
  path: /healthz/live
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  path: /healthz/ready
  initialDelaySeconds: 30
  periodSeconds: 5
