replicas: 2
port: 8081

image:
  repository: ""
  tag: "latest"

istio:
  enabled: false
  revision: ""

livenessProbe:
  path: /healthz/live
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  path: /healthz/ready
  initialDelaySeconds: 15
  periodSeconds: 5
