global:
  environment: dev

istio:
  enabled: false

image:
  apiGateway: ""  

apiGateway:
  replicas: 1

opentelemetry-collector:
  enabled: true
  config:
    exporters:
      otlp/tempo:
        endpoint: tempo:4317
        tls:
          insecure: true
      otlphttp/loki:
        endpoint: http://monitoring.svc.cluster.local:3100/otlp
        tls:
          insecure: true
      debug:
        verbosity: detailed
      prometheus:
        endpoint: localhost:8889
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [otlp/tempo]
        metrics:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [resource, batch]
          exporters: [debug, otlphttp/loki]
