---
apiVersion: v2
name: argocd-image-updater
description: argocd-image-updater cluster addon (upstream chart)
type: application
version: 0.1.0
dependencies:
  - name: argocd-image-updater
    version: "1.2.4"
    repository: https://argoproj.github.io/argo-helm
