---
apiVersion: v2
name: keda
description: keda cluster addon (upstream chart)
type: application
version: 0.1.0
dependencies:
  - name: keda
    version: "2.14.2"
    repository: https://kedacore.github.io/charts
