#!/usr/bin/env python3
"""Render GitOps manifests from the Terraform gitops_contract.

The contract (see saas-services-infra/docs/gitops-contract.md) is the single
source of truth for cluster identity and which RDS instances exist / which
Secrets Manager secret holds each one's master credentials. The output shapes
live in external templates under scripts/templates/*.tpl (so the YAML is never
hardcoded in this script); this fills the contract values into them per env:

  - provider-sql.{header,instance}.yaml.tpl -> crossplane provider-sql.yaml
  - karpenter-values.yaml.tpl               -> karpenter values-<env>.generated.yaml
  - keycloak-values.yaml.tpl                -> keycloak values-<env>.generated.yaml

Usage:
    scripts/render_gitops.py --contract contracts/gitops-contract.dev.json \\
        --out infra/overlays/dev/crossplane/provider-sql.yaml

Stdlib only — no third-party deps, safe to run in CI.
"""
import argparse
import json
import os
import sys

SUPPORTED_VERSION = 1

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")

BANNER = (
    "# ─────────────────────────────────────────────────────────────────────────────\n"
    "# GENERATED by scripts/render_gitops.py from the Terraform gitops_contract,\n"
    "# using the templates under scripts/templates/*.tpl.\n"
    "# Do not edit by hand — change the contract in saas-services-infra (or the\n"
    "# template) and re-render.\n"
    "# ─────────────────────────────────────────────────────────────────────────────\n"
)


def _load_tpl(name: str) -> str:
    with open(os.path.join(TEMPLATE_DIR, name)) as handle:
        return handle.read()


def _require_version(contract: dict) -> None:
    version = contract.get("version")
    if version != SUPPORTED_VERSION:
        raise SystemExit(
            f"unsupported contract version {version!r}; renderer supports {SUPPORTED_VERSION}"
        )


def render(contract: dict) -> str:
    _require_version(contract)
    databases = contract.get("databases") or {}
    if not databases:
        raise SystemExit("contract has no databases")

    header = _load_tpl("provider-sql.header.yaml.tpl")
    instance_tpl = _load_tpl("provider-sql.instance.yaml.tpl")

    out = [BANNER, header]
    for instance in sorted(databases):
        entry = databases[instance]
        secret_name = entry.get("secret_name")
        if not secret_name:
            raise SystemExit(f"database {instance!r} is missing secret_name")
        out.append(
            instance_tpl.replace("__INST__", instance).replace("__SECRET__", secret_name)
        )
    return "".join(out)


def _host_only(endpoint: str) -> str:
    """Strip a trailing :port from an RDS endpoint (the chart takes host + port separately)."""
    return endpoint.rsplit(":", 1)[0] if ":" in endpoint else endpoint


def render_keycloak_values(contract: dict) -> str:
    """Helm values setting the keycloak subchart's externalDatabase.host from the contract."""
    _require_version(contract)
    keycloak = (contract.get("databases") or {}).get("keycloak") or {}
    endpoint = keycloak.get("endpoint")
    if not endpoint:
        raise SystemExit("contract has no databases.keycloak.endpoint")
    body = _load_tpl("keycloak-values.yaml.tpl").replace("__HOST__", _host_only(endpoint))
    return BANNER + body


def render_karpenter_values(contract: dict) -> str:
    """Helm values setting karpenter's settings.clusterName + settings.interruptionQueue."""
    _require_version(contract)
    cluster = contract.get("cluster") or {}
    name = cluster.get("name")
    queue = cluster.get("karpenter_interruption_queue")
    if not name or not queue:
        raise SystemExit("contract.cluster needs both name and karpenter_interruption_queue")
    body = _load_tpl("karpenter-values.yaml.tpl").replace("__CLUSTER__", name).replace(
        "__QUEUE__", queue
    )
    return BANNER + body


def _write(path: str, text: str, label: str) -> None:
    with open(path, "w") as handle:
        handle.write(text)
    print(f"rendered {label} -> {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--contract", required=True, help="Path to gitops-contract JSON")
    parser.add_argument("--out", help="provider-sql output file (default: stdout if no other --*-out given)")
    parser.add_argument("--keycloak-out", help="keycloak values-<env>.generated.yaml output file")
    parser.add_argument("--karpenter-out", help="karpenter values-<env>.generated.yaml output file")
    args = parser.parse_args()

    with open(args.contract) as handle:
        contract = json.load(handle)

    wrote_any = False
    if args.out:
        _write(args.out, render(contract), f"{len(contract.get('databases', {}))} provider-sql instances")
        wrote_any = True
    if args.keycloak_out:
        _write(args.keycloak_out, render_keycloak_values(contract), "keycloak values")
        wrote_any = True
    if args.karpenter_out:
        _write(args.karpenter_out, render_karpenter_values(contract), "karpenter values")
        wrote_any = True

    if not wrote_any:
        sys.stdout.write(render(contract))


if __name__ == "__main__":
    main()
