#!/usr/bin/env python3
"""Render GitOps manifests from the Terraform gitops_contract.

The contract (see saas-services-infra/docs/gitops-contract.md) is the single
source of truth for which RDS instances exist and which Secrets Manager secret
holds each one's master credentials. This renders the Crossplane provider-sql
blocks (one ExternalSecret + one ProviderConfig per instance) so the instance
and secret names are never hand-kept in sync with Terraform again.

Usage:
    scripts/render_gitops.py --contract contracts/gitops-contract.dev.json \\
        --out infra/overlays/dev/crossplane/provider-sql.generated.yaml

Stdlib only — no third-party deps, safe to run in CI.
"""
import argparse
import json
import sys

SUPPORTED_VERSION = 1

HEADER = """# ─────────────────────────────────────────────────────────────────────────────
# GENERATED by scripts/render_gitops.py from the Terraform gitops_contract.
# Do not edit by hand — change the contract in saas-services-infra and re-render.
# ─────────────────────────────────────────────────────────────────────────────
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-sql
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-sql:v0.10.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
"""

# __INST__ and __SECRET__ are substituted; the {{ .field }} placeholders are
# External-Secrets Go templates and must survive verbatim into the output.
INSTANCE_BLOCK = """
# ─── __INST__ ───────────────────────────────────────────────────────────────
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-__INST__-admin
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-__INST__-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        data: |
          postgresql://{{ .username }}:{{ .password }}@{{ .endpoint }}/{{ .db_name }}?sslmode=require
        username: "{{ .username }}"
        password: "{{ .password }}"
        endpoint: "{{ .endpoint }}"
        db_name: "{{ .db_name }}"
  data:
    - { secretKey: username, remoteRef: { key: __SECRET__, property: username } }
    - { secretKey: password, remoteRef: { key: __SECRET__, property: password } }
    - { secretKey: endpoint, remoteRef: { key: __SECRET__, property: endpoint } }
    - { secretKey: db_name,  remoteRef: { key: __SECRET__, property: db_name  } }
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: rds-__INST__
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: crossplane-system
      name: rds-__INST__-admin
  sslMode: require
"""


def _require_version(contract: dict) -> None:
    version = contract.get("version")
    if version != SUPPORTED_VERSION:
        raise SystemExit(
            f"unsupported contract version {version!r}; renderer supports {SUPPORTED_VERSION}"
        )


def render(contract: dict) -> str:
    _require_version(contract)
    databases = contract.get("databases") or {}
    if not databases:
        raise SystemExit("contract has no databases")

    out = [HEADER]
    for instance in sorted(databases):
        entry = databases[instance]
        secret_name = entry.get("secret_name")
        if not secret_name:
            raise SystemExit(f"database {instance!r} is missing secret_name")
        block = INSTANCE_BLOCK.replace("__INST__", instance).replace(
            "__SECRET__", secret_name
        )
        out.append(block)
    return "".join(out)


PATCH_HEADER = (
    "# ─────────────────────────────────────────────────────────────────────────────\n"
    "# GENERATED by scripts/render_gitops.py from the Terraform gitops_contract.\n"
    "# Do not edit by hand — change the contract in saas-services-infra and re-render.\n"
    "# JSON6902 patch consumed by the addon overlay's kustomization.yaml.\n"
    "# ─────────────────────────────────────────────────────────────────────────────\n"
)

# Helm `parameters[]` indices in the addon base Applications these patches target.
KEYCLOAK_HOST_PARAM_INDEX = 1        # gitops/infra/keycloak/base/application.yaml
KARPENTER_CLUSTER_PARAM_INDEX = 0    # gitops/infra/karpenter/base/application.yaml
KARPENTER_QUEUE_PARAM_INDEX = 1


def _host_only(endpoint: str) -> str:
    """Strip a trailing :port from an RDS endpoint (the chart takes host + port separately)."""
    return endpoint.rsplit(":", 1)[0] if ":" in endpoint else endpoint


def render_keycloak_host_patch(contract: dict) -> str:
    """JSON6902 patch setting the keycloak Application's externalDatabase.host from the contract."""
    _require_version(contract)
    keycloak = (contract.get("databases") or {}).get("keycloak") or {}
    endpoint = keycloak.get("endpoint")
    if not endpoint:
        raise SystemExit("contract has no databases.keycloak.endpoint")
    host = _host_only(endpoint)
    return PATCH_HEADER + (
        "- op: replace\n"
        f"  path: /spec/source/helm/parameters/{KEYCLOAK_HOST_PARAM_INDEX}/value\n"
        f"  value: {host}\n"
    )


def render_karpenter_patch(contract: dict) -> str:
    """JSON6902 patch setting karpenter's settings.clusterName + settings.interruptionQueue."""
    _require_version(contract)
    cluster = contract.get("cluster") or {}
    name = cluster.get("name")
    queue = cluster.get("karpenter_interruption_queue")
    if not name or not queue:
        raise SystemExit("contract.cluster needs both name and karpenter_interruption_queue")
    return PATCH_HEADER + (
        "- op: replace\n"
        f"  path: /spec/source/helm/parameters/{KARPENTER_CLUSTER_PARAM_INDEX}/value\n"
        f"  value: {name}\n"
        "- op: replace\n"
        f"  path: /spec/source/helm/parameters/{KARPENTER_QUEUE_PARAM_INDEX}/value\n"
        f"  value: {queue}\n"
    )


def _write(path: str, text: str, label: str) -> None:
    with open(path, "w") as handle:
        handle.write(text)
    print(f"rendered {label} -> {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--contract", required=True, help="Path to gitops-contract JSON")
    parser.add_argument("--out", help="provider-sql output file (default: stdout if no other --*-out given)")
    parser.add_argument("--keycloak-out", help="keycloak externalDatabase.host JSON6902 patch output file")
    parser.add_argument("--karpenter-out", help="karpenter clusterName/interruptionQueue JSON6902 patch output file")
    args = parser.parse_args()

    with open(args.contract) as handle:
        contract = json.load(handle)

    wrote_any = False
    if args.out:
        _write(args.out, render(contract), f"{len(contract.get('databases', {}))} provider-sql instances")
        wrote_any = True
    if args.keycloak_out:
        _write(args.keycloak_out, render_keycloak_host_patch(contract), "keycloak host patch")
        wrote_any = True
    if args.karpenter_out:
        _write(args.karpenter_out, render_karpenter_patch(contract), "karpenter cluster patch")
        wrote_any = True

    if not wrote_any:
        sys.stdout.write(render(contract))


if __name__ == "__main__":
    main()
