#!/usr/bin/env python3
"""Switch an environment between the `render` and `eso` GitOps-contract delivery
modes deterministically, so nobody hand-copies value files or hand-deletes
generated ones. See docs/gitops-contract-delivery-modes.md.

    scripts/set-delivery-mode.py --env dev --mode eso
    scripts/set-delivery-mode.py --env dev --mode render

render -> eso: writes gitops/infra/karpenter/values-<env>.eso.yaml (and keycloak
for prod), removes the karpenter/keycloak values-<env>.generated.yaml, flips the
toggle, and runs the guard rail to self-verify.

eso -> render: removes the eso value files and flips the toggle. The
values-<env>.generated.yaml files are re-created by the render-gitops workflow
(it needs the contract from AWS), which the switch workflow runs for this direction.

The Crossplane provider-sql manifests are not touched — they are contract-generated
in both modes (see the scope note in check-delivery-mode.py).

Stdlib only; safe to run locally or in CI.
"""
import argparse
import glob
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENVS = ("dev", "staging", "prod")
MODES = ("render", "eso")

_BANNER = (
    "# GENERATED by scripts/set-delivery-mode.py (eso delivery mode). Do not edit\n"
    "# by hand — re-run the switch. See docs/gitops-contract-delivery-modes.md.\n"
)

KARPENTER_ESO = _BANNER + """\
gitopsContract:
  eso:
    enabled: true
    secretName: saas/{env}/infra-contract

karpenter:
  # settings.clusterName / interruptionQueue stay unset; CLUSTER_NAME and
  # INTERRUPTION_QUEUE come from the karpenter-contract Secret via controller.env.
  controller:
    env:
      - name: CLUSTER_NAME
        valueFrom:
          secretKeyRef:
            name: karpenter-contract
            key: CLUSTER_NAME
      - name: INTERRUPTION_QUEUE
        valueFrom:
          secretKeyRef:
            name: karpenter-contract
            key: INTERRUPTION_QUEUE
"""

KEYCLOAK_ESO = _BANNER + """\
gitopsContract:
  eso:
    enabled: true
    secretName: saas/{env}/infra-contract

keycloakx:
  # database.hostname stays unset (dbchecker is off); KC_DB_URL_HOST is supplied
  # from the keycloak-contract Secret via extraEnvFrom. The base extraEnv
  # (bootstrap admin) is untouched.
  extraEnvFrom: |
    - secretRef:
        name: keycloak-contract
"""

# chart -> (eso file body, envs that get an eso file)
ESO_CHARTS = {
    "karpenter": (KARPENTER_ESO, ("dev", "staging", "prod")),
    "keycloak": (KEYCLOAK_ESO, ("prod",)),
}


def p(*parts):
    return os.path.join(REPO, *parts)


def _write(path, text):
    with open(path, "w") as handle:
        handle.write(text)
    print(f"  wrote   {os.path.relpath(path, REPO)}")


def _remove(path):
    if os.path.exists(path):
        os.remove(path)
        print(f"  removed {os.path.relpath(path, REPO)}")


def _eso_path(chart, env):
    return p("gitops", "infra", chart, f"values-{env}.eso.yaml")


def _generated_value_files(env):
    return glob.glob(p("gitops", "infra", "*", f"values-{env}.generated.yaml"))


def _mode_file(env):
    return p("contracts", f"delivery-mode.{env}")


def _read_mode(env):
    return open(_mode_file(env)).read().strip() if os.path.exists(_mode_file(env)) else None


def to_eso(env):
    print(f"switching {env} -> eso")
    for chart, (body, envs) in ESO_CHARTS.items():
        if env in envs:
            _write(_eso_path(chart, env), body.format(env=env))
    for f in _generated_value_files(env):
        _remove(f)


def to_render(env):
    print(f"switching {env} -> render")
    for chart in ESO_CHARTS:
        _remove(_eso_path(chart, env))
    print(
        "  NOTE: values-<env>.generated.yaml is re-created by the render-gitops "
        "workflow (it needs the contract from AWS)."
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--env", required=True, choices=ENVS)
    ap.add_argument("--mode", required=True, choices=MODES)
    args = ap.parse_args()

    if _read_mode(args.env) == args.mode:
        print(f"{args.env} is already in '{args.mode}' mode; nothing to do.")
        return

    (to_eso if args.mode == "eso" else to_render)(args.env)
    _write(_mode_file(args.env), f"{args.mode}\n")

    print("\nrunning guard rail...")
    if subprocess.call([sys.executable, p("scripts", "check-delivery-mode.py")]) != 0:
        sys.exit("\nguard rail failed — see errors above; tree left as-is for inspection.")
    print(f"\n{args.env} is now in '{args.mode}' mode. Review the diff and open a PR.")


if __name__ == "__main__":
    main()
