apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application/applications.yaml
  - observability/grafana-stack/application-prometheus.yaml
  - observability/grafana-stack/application-loki.yaml
  - keycloak/deployment.yaml
  - keycloak/service.yaml
  - keycloak/keycloak-app.yaml
  - airflow/airflow.yaml
  - airflow/deployment.yaml
  - airflow/service.yaml
