apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/refresh: hard
spec:
  project: default
  source:
    repoURL: https://github.com/huzaifa678/SAAS-Continious-Delivery.git
    targetRevision: main
    path: saas-chart
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: saas-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: oci://123456789.dkr.ecr.us-east-1.amazonaws.com/helm
      chart: auth-service
      targetRevision: 0.1.0
      helm:
        releaseName: auth-service
        valueFiles:
          - $values/charts/auth-service/values.yaml
          - $values/charts/auth-service/values-staging.yaml
    - repoURL: https://github.com/huzaifa678/SAAS-Continious-Delivery.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: saas-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: billing-service-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: oci://123456789.dkr.ecr.us-east-1.amazonaws.com/helm
      chart: billing-service
      targetRevision: 0.1.0
      helm:
        releaseName: billing-service
        valueFiles:
          - $values/charts/billing-service/values.yaml
          - $values/charts/billing-service/values-staging.yaml
    - repoURL: https://github.com/huzaifa678/SAAS-Continious-Delivery.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: saas-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subscription-service-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: oci://123456789.dkr.ecr.us-east-1.amazonaws.com/helm
      chart: subscription-service
      targetRevision: 0.1.0
      helm:
        releaseName: subscription-service
        valueFiles:
          - $values/charts/subscription-service/values.yaml
          - $values/charts/subscription-service/values-staging.yaml
    - repoURL: https://github.com/huzaifa678/SAAS-Continious-Delivery.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: saas-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usage-service-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: oci://123456789.dkr.ecr.us-east-1.amazonaws.com/helm
      chart: usage-service
      targetRevision: 0.1.0
      helm:
        releaseName: usage-service
        valueFiles:
          - $values/charts/usage-service/values.yaml
          - $values/charts/usage-service/values-staging.yaml
    - repoURL: https://github.com/huzaifa678/SAAS-Continious-Delivery.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: saas-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.21.2
      helm:
        releaseName: istio-base
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.21.2
      helm:
        releaseName: istiod
        values: |
          pilot:
            env:
              PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
