replicas: 3

image:
  repository: ""  
  tag: "prod"

istio:
  enabled: true
  revision: ""

livenessProbe:
  path: /healthz/live
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  path: /healthz/ready
  initialDelaySeconds: 10
  periodSeconds: 5
