apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application/applications.yaml
  - observability/elk-stack/application-elasticsearch.yaml
  - observability/elk-stack/application-kibana.yaml
