---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base post-renderer for the karpenter addon; Helm output is injected by ArgoCD.
commonLabels:
  managed-by: argocd
  addon: karpenter
