---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchExpressions:
            - { key: env, operator: Exists }
  template:
    metadata:
      name: 'infra-{{.metadata.labels.env}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      source:
        repoURL: https://github.com/huzaifa678/SAAS-Continious-Delivery.git
        targetRevision: main
        path: 'infra/overlays/{{.metadata.labels.env}}'
      destination:
        server: '{{.server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
