---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  stack-grafana: "true"
          - git:
              repoURL: https://github.com/huzaifa678/SAAS-Continious-Delivery.git
              revision: main
              files:
                - path: gitops/observability/grafana/*/app.yaml
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  stack-elk: "true"
          - git:
              repoURL: https://github.com/huzaifa678/SAAS-Continious-Delivery.git
              revision: main
              files:
                - path: gitops/observability/elk/*/app.yaml
  template:
    metadata:
      name: '{{.path.basename}}-{{.metadata.labels.env}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/huzaifa678/SAAS-Continious-Delivery.git
        targetRevision: main
        path: '{{.path.path}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - 'values-{{.metadata.labels.env}}.yaml'
          # Kustomize post-renderer (path mirrors the chart dir under post-renderer/).
          postRenderer:
            kustomize:
              dir: '{{ .path.path | replace "gitops/" "post-renderer/" }}/overlays/{{.metadata.labels.env}}'
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
