apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - observability/application-elasticsearch.yaml
  - observability/application-kibana.yaml
  - keda/application-keda.yaml
  - argo-rollouts/application-argo-rollouts.yaml
  - crossplane/application-crossplane.yaml
  - crossplane/provider-sql.yaml
